<?php

/** Implements hook_preprocess_block().
 * @param $variables
 */
function swm_config_preprocess_block(&$variables) {

  // Add id to block titles of views
  if ($variables['base_plugin_id'] == 'views_block' && isset($variables['content']['#display_id'])) {
    $variables['title_attributes']['id'] = $variables['content']['#display_id'];
  }

  if ($variables['configuration']['id'] == 'config_block' || $variables['base_plugin_id'] == 'views_block') {
      $variables['attributes']['class'] = 'tl-region';
  }

}

/**
 * @param                                      $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param                                      $form_id
 */
function swm_config_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['actions']['submit']['#value'] = t("Let's go");
    $form['#title'] = t("Register");
  }

  if ($form_id == 'user_login_form') {
    $form['actions']['submit']['#value'] = t("Connect");
    $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
  }

  if ($form_id == 'user_pass') {
    $form['actions']['submit']['#value'] = t("Reset");
    $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
    $form['#title'] = t('Get password');
  }
}
