name: 'SWM Config'
type: module
core: 8.x
dependencies:
  - admin_toolbar
  - admin_toolbar_tools
  - block
  - block_content
  - comment
  - content_translation
  - ctools_block
  - editor
  - field
  - file
  - filter
  - ginvite
  - group
  - help
  - image
  - language
  - menu_link_content
  - node
  - page_manager
  - panels
  - path
  - pathauto
  - rdf
  - registration_link
  - rules
  - simple_block
  - swm_groups
  - system
  - taxonomy
  - text
  - typed_data
  - user
  - views
  - betterlogin
package: SWM
