name: 'SWM Config'
type: module
core: 8.x
dependencies:
  - block
  - block_content
  - comment
  - content_translation
  - field
  - file
  - group
  - help
  - image
  - language
  - menu_link_content
  - node
  - page_manager
  - panels
  - path
  - pathauto
  - rdf
  - swm_config
  - system
  - taxonomy
  - text
  - user
  - views
